---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
      annotations:
        container.apparmor.security.beta.kubernetes.io/whoami: runtime/default
    spec:
      containers:
        - name: whoami
          image: moustafabendjema/express
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
      # whoami is listening on 8080 from --port argument so that non-root user
      # can run container as needs to bind to ports higher than 1024
      targetPort: 3000
  selector:
    app: whoami
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver

spec:
  rules:
    - host: whoami.devuops.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80